# Generated by Django 4.2.5 on 2023-09-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
